import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const phases = [
  {
    code: 'F00', name: 'Adquisición y Pre-Desarrollo', groupName: 'PRE-OBRA', order: 0,
    items: [
      { itemCode: '00.01', activity: 'Compra del lote', description: 'Costo del lote vacío. Financiado con Alto Capital. Verificar HUD-1 original.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '00.02', activity: 'Closing del lote', description: 'Gastos del closing de compra del lote: title, recording fees, attorney fees.', responsable: 'Title Co', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '00.03', activity: 'Análisis de zonificación', description: 'Verificar setbacks, altura, FAR, restricciones HOA. Crítico antes del diseño.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '00.04', activity: 'Estudio de suelos', description: 'Análisis geotécnico del suelo. Opcional pero recomendado en lotes con pendiente.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '00.05', activity: 'Factibilidad de servicios', description: 'Verificar acceso a agua, sewer (grinder pump), electricidad, internet. Definir TAP costs.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '00.06', activity: 'Validación HOA Chickasaw', description: 'Confirmar buen standing, cuotas al día, cumplimiento plan HOA, impact fees.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '00.07', activity: 'Modelo financiero pre-compra', description: 'Análisis ARV vs budget vs costos financiamiento. Determina viabilidad del deal.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '00.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 8 },
      { itemCode: '00.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 9 },
    ],
  },
  {
    code: 'F01', name: 'Financiamiento y Préstamo', groupName: 'PRE-OBRA', order: 1,
    items: [
      { itemCode: '01.01', activity: 'Solicitud de Construction Loan', description: 'Aplicación al préstamo con Hera: estados financieros, score, planes, budget, ARV appraisal.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '01.02', activity: 'LOI / Loan Approval Letter', description: 'Documento oficial Hera con términos: monto, tasa, plazo, holdback, draw schedule. Loan #HERA-2026-0066.', responsable: 'Hera Holdings', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '01.03', activity: 'Origination Fee', description: '2.5% del loan amount = ~$10,059. Non-refundable. Ya pagado en closing.', responsable: 'Hera Holdings', unit: '%', valorPresupuestado: 0, order: 3 },
      { itemCode: '01.04', activity: 'Underwriting Fee', description: 'Cargo por evaluar riesgo del préstamo. Ya pagado.', responsable: 'Hera Holdings', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '01.05', activity: 'Processing Fee', description: 'Cargo administrativo por procesar documentación. Ya pagado.', responsable: 'Hera Holdings', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '01.06', activity: 'Service Fee', description: 'Cargo del loan servicer. Ya pagado.', responsable: 'Hera Holdings', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '01.07', activity: 'Legal Fee', description: 'Abogado del lender prepara documentos del préstamo. Ya pagado.', responsable: 'Hera Holdings', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '01.08', activity: 'Budget Review/Permit Validation', description: 'Trinity revisa budget y valida permits antes del primer draw. Ya pagado.', responsable: 'Hera/Trinity', unit: 'LS', valorPresupuestado: 0, order: 8 },
      { itemCode: '01.09', activity: 'Inspection Fee inicial', description: 'Primera visita Trinity para validar sitio, permit activo, budget. Ya pagado.', responsable: 'Trinity', unit: 'LS', valorPresupuestado: 0, order: 9 },
      { itemCode: '01.10', activity: 'Interest Reserve', description: '$5,000 pre-fondeado por Hera para cubrir intereses iniciales. En closing.', responsable: 'Hera Holdings', unit: 'LS', valorPresupuestado: 0, order: 10 },
      { itemCode: '01.11', activity: 'Insurance Monitoring Fee', description: 'Hera verifica trimestralmente vigencia de pólizas. Ya pagado.', responsable: 'Hera Holdings', unit: 'LS', valorPresupuestado: 0, order: 11 },
      { itemCode: '01.12', activity: 'Daily interest pre-funding', description: 'Intereses desde closing hasta primer wire. Ya pagado.', responsable: 'Hera Holdings', unit: 'LS', valorPresupuestado: 0, order: 12 },
      { itemCode: '01.13', activity: 'Closing - Settlement Fee', description: 'Guest & Brady LLC por manejar closing del préstamo. Ya pagado.', responsable: 'Guest & Brady LLC', unit: 'LS', valorPresupuestado: 0, order: 13 },
      { itemCode: '01.14', activity: "Lender's Title Insurance", description: 'Póliza que protege al lender contra defectos en el título. Ya pagado.', responsable: 'Title Company', unit: 'LS', valorPresupuestado: 0, order: 14 },
      { itemCode: '01.15', activity: 'Title - Search/Abstract', description: 'Investigación histórica del título. Ya pagado.', responsable: 'Title Company', unit: 'LS', valorPresupuestado: 0, order: 15 },
      { itemCode: '01.16', activity: 'Technology Fee', description: 'Cargo por e-signature, e-recording. Ya pagado.', responsable: 'Title Company', unit: 'LS', valorPresupuestado: 0, order: 16 },
      { itemCode: '01.17', activity: 'Title Administrative Fee', description: 'Cargo administrativo title company. Ya pagado.', responsable: 'Title Company', unit: 'LS', valorPresupuestado: 0, order: 17 },
      { itemCode: '01.18', activity: 'Title - Exam Fee', description: 'Attorney que certifica título limpio. Ya pagado.', responsable: 'Title Attorney', unit: 'LS', valorPresupuestado: 0, order: 18 },
      { itemCode: '01.19', activity: 'Title Commitment Fee', description: 'Emisión del title commitment. Ya pagado.', responsable: 'Title Company', unit: 'LS', valorPresupuestado: 0, order: 19 },
      { itemCode: '01.20', activity: 'CPL (Lender)', description: 'Garantía del title underwriter al lender contra fraude/errores en closing. Ya pagado.', responsable: 'Title Underwriter', unit: 'LS', valorPresupuestado: 0, order: 20 },
      { itemCode: '01.21', activity: 'Recording Mortgage', description: 'Oconee County registra mortgage (gravamen) de Hera sobre la propiedad. Ya pagado.', responsable: 'Oconee County', unit: 'LS', valorPresupuestado: 0, order: 21 },
      { itemCode: '01.22', activity: 'E-Record Fee Deed', description: 'Registro electrónico del deed en el condado. Ya pagado.', responsable: 'Oconee County', unit: 'LS', valorPresupuestado: 0, order: 22 },
      { itemCode: '01.23', activity: 'E-Record Fee Mortgage', description: 'Registro electrónico de mortgage. Ya pagado.', responsable: 'Oconee County', unit: 'LS', valorPresupuestado: 0, order: 23 },
      { itemCode: '01.24', activity: 'Cash at Settlement (equity)', description: 'Aporte propio en closing: $13,349.36. Capital 100% tuyo, no reembolsable.', responsable: 'Acosta Trust Homes', unit: 'LS', valorPresupuestado: 13349.36, order: 24 },
      { itemCode: '01.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 25 },
      { itemCode: '01.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 26 },
    ],
  },
  {
    code: 'F02', name: 'Seguros y Pólizas', groupName: 'PRE-OBRA', order: 2,
    items: [
      { itemCode: '02.01', activity: "Builder's Risk Insurance", description: 'OBLIGATORIO. Cubre daños al edificio durante construcción. Exigido por Hera. COI requerido para draws.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '02.02', activity: 'General Liability (GL)', description: 'Cubre daños a terceros. Hera lo exige. Cotizado $4,816.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 4816, order: 2 },
      { itemCode: '02.03', activity: 'GL - Earned Taxes/Fees', description: 'Impuestos estatales SC (~5%) sobre prima de GL.', responsable: 'Insurance broker', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '02.04', activity: 'GL - Finance Taxes/Fees', description: 'Fee de financiación si se financia la prima en cuotas.', responsable: 'Insurance broker', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '02.05', activity: 'Workers Compensation', description: 'Obligatorio en SC si hay empleados. GC debe certificar que sus subs tienen WC.', responsable: 'AMA, LLC (GC)', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '02.06', activity: 'Acord Certificate', description: 'Recopilar COIs de todos los subs. Sin costo directo pero esencial.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '02.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '02.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 8 },
    ],
  },
  {
    code: 'F03', name: 'Contratos y Acuerdos', groupName: 'PRE-OBRA', order: 3,
    items: [
      { itemCode: '03.01', activity: 'Construction Agreement con GC', description: 'Contrato escrito con AMA LLC. Alcance, precio, cronograma, hitos de pago, change orders, warranties. CRÍTICO antes de obra.', responsable: 'AMA, LLC', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '03.02', activity: 'Verificación Builder License SC', description: 'Verificar en SC LLR que AMA, LLC tiene licencia activa, sin sanciones, cubre tipo de proyecto.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '03.03', activity: 'W-9 del GC', description: 'IRS form para reportar pagos en 1099 al final del año. Sin W-9, no se debe pagar.', responsable: 'AMA, LLC', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '03.04', activity: 'Lien Waivers protocolo', description: 'Cada pago a sub/supplier requiere signed lien waiver. Protección #1 del owner contra mechanic\'s liens.', responsable: 'All subs', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '03.05', activity: 'Subcontractor agreements', description: 'Si contratas subs directamente, cada uno necesita contrato. Si todo va por GC, exigirlo en contrato del GC.', responsable: 'AMA, LLC', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '03.06', activity: 'Schedule of Values', description: 'Descomposición del costo total en line items. Trinity inspecciona contra el SOV para aprobar draws. PEDIR COPIA OFICIAL.', responsable: 'Trinity', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '03.07', activity: 'Cronograma de obra firmado', description: 'Cronograma con fechas por fase, firmado GC y owner. Hera lo puede pedir como anexo.', responsable: 'Owner + AMA', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '03.08', activity: 'Change Order Protocol', description: 'Procedimiento documentado para COs. Sin protocolo, los COs verbales generan conflictos al final.', responsable: 'Owner + AMA', unit: 'LS', valorPresupuestado: 0, order: 8 },
      { itemCode: '03.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 9 },
      { itemCode: '03.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 10 },
    ],
  },
  {
    code: 'F04', name: 'Diseño, Permisos y Soft Costs', groupName: 'PRE-OBRA', order: 4,
    items: [
      { itemCode: '04.01', activity: 'Survey topográfico', description: 'Mapa profesional del lote: límites, elevaciones, árboles, utilidades, setbacks. Necesario para diseño y HOA.', responsable: 'Licensed Surveyor SC', unit: 'LS', valorPresupuestado: 3000, order: 1 },
      { itemCode: '04.02', activity: 'Diseño y blueprints', description: 'Plans completos. Stock plan HPZ #2400-5 Crawlspace. Incluye plantas, elevaciones, secciones, structural.', responsable: 'HPZ Plans', unit: 'LS', valorPresupuestado: 3500, order: 2 },
      { itemCode: '04.03', activity: 'GC Fee', description: 'Fee fijo de AMA LLC por gerencia del proyecto: coordinación subs, supervisión, scheduling. $12,000.', responsable: 'AMA, LLC', unit: 'LS', valorPresupuestado: 12000, order: 3 },
      { itemCode: '04.04', activity: 'County Building Permit', description: 'Permit Oconee County BR26-000029. Vence 27-Jul-2026. Sin esto NO se puede empezar.', responsable: 'Oconee County', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '04.05', activity: 'HOA Building Permit', description: 'Aprobación ACC Chickasaw Point: plans, materiales, colores, landscaping. Incluye impact fees y compliance deposits.', responsable: 'Chickasaw POA', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '04.06', activity: 'Water TAP Permit', description: 'Pago por conectar línea de agua del street main al lote. One-time fee.', responsable: 'Chickasaw Utility', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '04.07', activity: 'Sewer/Grinder Pump TAP', description: 'TAP fee para conexión al sistema de grinder pump pressurizado de Chickasaw.', responsable: 'Chickasaw Utility', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '04.08', activity: 'ACC Approval (Chickasaw)', description: 'Aprobación del Architectural Compliance Committee. Sin esto, HOA puede parar la obra.', responsable: 'Chickasaw ACC', unit: 'LS', valorPresupuestado: 0, order: 8 },
      { itemCode: '04.09', activity: 'Color/Material Approval ACC', description: 'Pre-aprobación de colores y materiales exteriores por ACC. Obligatorio antes de instalar.', responsable: 'Chickasaw ACC', unit: 'LS', valorPresupuestado: 0, order: 9 },
      { itemCode: '04.10', activity: 'Drainage Plan Submission', description: 'Plan de drenaje aprobado por Oconee County. Parte del design package.', responsable: 'Civil Engineer', unit: 'LS', valorPresupuestado: 0, order: 10 },
      { itemCode: '04.11', activity: 'Landscaping Plan Submission', description: 'Plan de landscaping aprobado por ACC. Requerido antes del CO.', responsable: 'Landscape designer', unit: 'LS', valorPresupuestado: 0, order: 11 },
      { itemCode: '04.12', activity: 'Chickasaw Utility Approval', description: 'Aprobación de Chickasaw Point Utilities antes de pour foundation.', responsable: 'Chickasaw Utility', unit: 'LS', valorPresupuestado: 0, order: 12 },
      { itemCode: '04.13', activity: '24h POA Notification (Pre-Pour)', description: 'Notificación obligatoria 24h al POA Chickasaw ANTES de cada pour de concreto. CRÍTICO.', responsable: 'Owner/GC', unit: 'LS', valorPresupuestado: 0, order: 13 },
      { itemCode: '04.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 14 },
      { itemCode: '04.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 15 },
    ],
  },
  {
    code: 'F05', name: 'Preliminares de Obra', groupName: 'OBRA', order: 5,
    items: [
      { itemCode: '05.01', activity: 'Temporary Power Pole', description: 'Poste eléctrico temporal para obra. Blue Ridge Electric (864-878-6326). Electricista licenciado lo instala.', responsable: 'Licensed Electrician', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '05.02', activity: 'Temp Power Approval', description: 'Aprobación de Blue Ridge Electric del poste temporal. Debe estar antes del sitework.', responsable: 'Blue Ridge Electric', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '05.03', activity: 'Portable Toilet', description: 'Porta-john en obra durante toda la construcción. ~$125/mes x meses de obra.', responsable: 'Owner/GC', unit: 'MO', valorPresupuestado: 750, order: 3 },
      { itemCode: '05.04', activity: '811 Utility Locate Call', description: 'OBLIGATORIO en SC antes de excavar. Marca líneas enterradas. Sin esto es ilegal cavar.', responsable: 'GC/Owner', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '05.05', activity: 'Termite Pre-Treatment', description: 'Tratamiento preventivo de termitas antes de footings/slab. Obligatorio en SC para financiamiento.', responsable: 'Licensed pest control', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '05.06', activity: 'Site Address Numbers Posted', description: 'Número de dirección visible en el lote. Requerido por código de Oconee County.', responsable: 'Owner/GC', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '05.07', activity: 'Construction Signage', description: 'Letrero visible con número de permit en el sitio. Requerido por Oconee County.', responsable: 'GC', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '05.08', activity: 'Security Cameras (Optional)', description: 'Cámaras de seguridad en obra para monitoreo remoto y protección. Altamente recomendado.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 8 },
      { itemCode: '05.09', activity: 'Storage Container / Job Box', description: 'Contenedor para almacenar materiales y herramientas en obra. Renta o compra.', responsable: 'Owner/GC', unit: 'LS', valorPresupuestado: 0, order: 9 },
      { itemCode: '05.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 10 },
      { itemCode: '05.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 11 },
    ],
  },
  {
    code: 'F06', name: 'Preparación del Sitio', groupName: 'OBRA', order: 6,
    items: [
      { itemCode: '06.01', activity: 'Lot Clearing', description: 'Limpieza del lote: árboles, vegetación, escombros. Acceso para equipos pesados.', responsable: 'Excavator/Site contractor', unit: 'LS', valorPresupuestado: 20000, order: 1 },
      { itemCode: '06.02', activity: 'Grading', description: 'Nivelación del terreno para drenaje correcto. Drenaje debe alejarse de la casa (positive drainage).', responsable: 'Excavator/Grader', unit: 'LS', valorPresupuestado: 14100, order: 2 },
      { itemCode: '06.03', activity: 'Temporary Gravel Driveway', description: 'Acceso de grava temporal para equipos pesados. Evita daño al sewer y al lote.', responsable: 'Contractor', unit: 'LS', valorPresupuestado: 5400, order: 3 },
      { itemCode: '06.04', activity: 'Silt Fence', description: 'Malla de control de erosión. Obligatorio por código de SC antes de cualquier grading.', responsable: 'Site contractor', unit: 'LF', valorPresupuestado: 1500, order: 4 },
      { itemCode: '06.05', activity: 'Setback Verification', description: 'Verificar setbacks físicos antes de marcar footings. Error aquí = multa o demolición.', responsable: 'Surveyor', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '06.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '06.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 7 },
    ],
  },
  {
    code: 'F07', name: 'Cimentación / Foundation', groupName: 'OBRA', order: 7,
    items: [
      { itemCode: '07.01', activity: 'Excavation and Compaction', description: 'Excavación del área de footings y compactación del subgrade. Base para toda la estructura.', responsable: 'Excavator', unit: 'LS', valorPresupuestado: 9400, order: 1 },
      { itemCode: '07.02', activity: 'Slab Framing (Forms)', description: 'Formas desmontables para slab y footings. Deben ser precisas para que el layout sea correcto.', responsable: 'Concrete contractor', unit: 'LS', valorPresupuestado: 1900, order: 2 },
      { itemCode: '07.03', activity: 'Fill Dirt', description: '~60 yards cúbicas estimadas para nivelación bajo slab y alrededor de fundación.', responsable: 'Dirt supplier', unit: 'CY', valorPresupuestado: 2400, order: 3 },
      { itemCode: '07.04', activity: 'Gravel Base', description: 'Cama de gravilla bajo slab para drenaje y soporte. ~57 tons o según spec.', responsable: 'Stone supplier', unit: 'CY', valorPresupuestado: 3500, order: 4 },
      { itemCode: '07.05', activity: 'Underground Plumbing', description: 'Plomería bajo slab (DWV lines) antes del pour. BLOQUEA el pour si no está inspeccionada.', responsable: 'Plumber', unit: 'LS', valorPresupuestado: 4700, order: 5 },
      { itemCode: '07.06', activity: 'Slab Construction', description: 'Vaciado de slab de concreto. 4" thickness mínimo. Requiere inspección previa.', responsable: 'Concrete contractor', unit: 'LS', valorPresupuestado: 18000, order: 6 },
      { itemCode: '07.07', activity: 'Crawlspace Walls / Foundation', description: 'Muros de fundación del crawlspace según plan HPZ. Incluye vents, access door.', responsable: 'Foundation contractor', unit: 'LS', valorPresupuestado: 39600, order: 7 },
      { itemCode: '07.08', activity: 'Footing Inspection (County)', description: 'Inspección de Oconee County antes del vaciado de footings. BLOQUEA EL POUR.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 8 },
      { itemCode: '07.09', activity: 'Foundation Steel Inspection', description: 'Inspección del rebar/rods antes del pour de muros. Pre-pour obligatorio.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 9 },
      { itemCode: '07.10', activity: 'Plumbing Under Slab Inspection', description: 'Inspección de plomería bajo slab con pressure test. Antes de cerrar el slab.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 10 },
      { itemCode: '07.11', activity: 'Electrical Under Slab Inspection', description: 'Inspección de conduit eléctrico bajo slab antes del pour. Si aplica.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 11 },
      { itemCode: '07.12', activity: 'Pre-Slab Inspection', description: 'Inspección final de todo antes del pour del slab de piso. Checklist completo.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 12 },
      { itemCode: '07.13', activity: 'Foundation / Damp Proofing', description: 'Impermeabilización exterior de muros de crawlspace. Crítico para control de humedad.', responsable: 'Foundation contractor', unit: 'LS', valorPresupuestado: 0, order: 13 },
      { itemCode: '07.14', activity: 'J-Bolts / Anchor Bolts', description: 'Pernos de anclaje en el top de los muros para fijar el framing. Wind code SC.', responsable: 'Foundation contractor', unit: 'LS', valorPresupuestado: 0, order: 14 },
      { itemCode: '07.15', activity: '24h HOA Notification (Pre-Pour)', description: 'Notificación obligatoria 24h al POA Chickasaw antes de CADA pour. Cada vez.', responsable: 'Owner/GC', unit: 'LS', valorPresupuestado: 0, order: 15 },
      { itemCode: '07.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 16 },
      { itemCode: '07.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 17 },
    ],
  },
  {
    code: 'F08', name: 'Framing / Estructura', groupName: 'OBRA', order: 8,
    items: [
      { itemCode: '08.01', activity: 'Lumber and Materials', description: 'Compra de madera: 2x4, 2x6, LVL, OSB, etc. Solo materiales. 84 Lumber / Builders FirstSource.', responsable: 'GC/Owner', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '08.02', activity: 'Framing Labor', description: 'Labor del framing crew. Solo mano de obra, separado de materiales.', responsable: 'Framing crew', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '08.03', activity: 'Floor System / Joists', description: 'Sistema de piso del crawlspace: joists, rim board, bearing. Primer nivel antes del subfloor.', responsable: 'Framing crew', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '08.04', activity: 'Wall Framing', description: 'Framing de todas las paredes exteriores e interiores. 2x4 per plan HPZ.', responsable: 'Framing crew', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '08.05', activity: 'Roof Trusses Install', description: 'Entrega e instalación de trusses prefabricados. Coordinación con truss supplier.', responsable: 'Truss supplier + framers', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '08.06', activity: 'Roof Sheathing', description: 'OSB/plywood sobre trusses antes de house wrap y roofing. Debe estar antes de la lluvia.', responsable: 'Framing crew', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '08.07', activity: 'Wall Sheathing / Zip System', description: 'Sheathing + house wrap integrado. Zip System recomendado para air sealing y agua.', responsable: 'Framing crew', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '08.08', activity: 'Windows and Exterior Doors', description: 'Instalación de ventanas y puertas exteriores. Hacen la casa dry antes de rough-ins.', responsable: 'Framing/Carpenter', unit: 'LS', valorPresupuestado: 0, order: 8 },
      { itemCode: '08.09', activity: 'Roofing', description: 'Instalación de roofing system: underlayment, shingles (30yr architectural), flashing, ridge cap.', responsable: 'Roofing contractor', unit: 'LS', valorPresupuestado: 0, order: 9 },
      { itemCode: '08.10', activity: 'Framing Inspection', description: 'Inspección de Oconee County. 100% framing completo incl. roof sheathing. BLOQUEA house wrap.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 10 },
      { itemCode: '08.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 11 },
      { itemCode: '08.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 12 },
    ],
  },
  {
    code: 'F09', name: 'Exterior Finishes', groupName: 'OBRA', order: 9,
    items: [
      { itemCode: '09.01', activity: 'Siding Installation', description: 'Instalación de siding exterior según aprobación ACC. Fiber cement (HardiePlank) recomendado en SC.', responsable: 'Siding contractor', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '09.02', activity: 'Exterior Trim', description: 'Trim exterior: corners, fascia, soffit, window trim. Parte del paquete de siding/carpintería.', responsable: 'Carpenter/Siding', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '09.03', activity: 'Gutters and Downspouts', description: 'Canaletas y bajantes. Crítico para control de agua y protección de la fundación.', responsable: 'Gutter contractor', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '09.04', activity: 'Porch/Deck Framing & Decking', description: 'Framing y decking de porches según plan. 656 SF de porches en el plan HPZ.', responsable: 'Framing/Carpenter', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '09.05', activity: 'Porch Railings', description: 'Railings de porches. Deben cumplir código (36" mínimo si >30" de altura).', responsable: 'Carpenter', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '09.06', activity: 'Exterior Paint / Stain', description: 'Pintura exterior o stain. Color aprobado previamente por ACC de Chickasaw.', responsable: 'Painter', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '09.07', activity: 'Driveway (Permanent)', description: 'Driveway permanente: concreto o asfalto según HOA rules. Reemplaza el temporal de grava.', responsable: 'Paving contractor', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '09.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 8 },
      { itemCode: '09.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 9 },
      { itemCode: '09.X3', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 10 },
    ],
  },
  {
    code: 'F10', name: 'Major Systems — MEP', groupName: 'OBRA', order: 10,
    items: [
      { itemCode: '10.01', activity: 'Plumbing Rough-In', description: 'DWV (drain-waste-vent) + supply lines. Todos los rough-ins antes de insulation. Pressure test requerido.', responsable: 'Plumber', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '10.02', activity: 'Electrical Rough-In', description: '100% rough eléctrico: panel, home runs, outlets, switches. Antes de insulation. BLOQUEA drywall.', responsable: 'Electrician', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '10.03', activity: 'HVAC Rough-In', description: 'Ductwork + líneas de refrigerante + returns + AHU location. Antes de insulation.', responsable: 'HVAC contractor', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '10.04', activity: 'Rough Plumbing Inspection', description: 'DWV + supply + pressure test inspeccionado por Oconee County. BLOQUEA insulation.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '10.05', activity: 'Rough Electrical Inspection', description: '100% rough eléctrico inspeccionado. BLOQUEA insulation.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '10.06', activity: 'Rough HVAC Inspection', description: 'Ductwork + líneas refrigerante inspeccionadas. BLOQUEA insulation.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '10.07', activity: 'Gas Lines (si aplica)', description: 'Si hay propano/gas natural, rough-in de líneas antes de drywall.', responsable: 'Plumber/Gas contractor', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '10.08', activity: 'Low Voltage / Data Rough-In', description: 'Pre-wiring para TV, internet, alarma, cámaras, audio. Antes de drywall.', responsable: 'Low voltage tech', unit: 'LS', valorPresupuestado: 0, order: 8 },
      { itemCode: '10.09', activity: 'Blocking for Fixtures', description: 'Blocking en paredes para grab bars, cabinets pesados, railings. Antes de drywall.', responsable: 'Framing/Carpenter', unit: 'LS', valorPresupuestado: 0, order: 9 },
      { itemCode: '10.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 10 },
      { itemCode: '10.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 11 },
      { itemCode: '10.X3', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 12 },
    ],
  },
  {
    code: 'F11', name: 'Insulation & Drywall', groupName: 'OBRA', order: 11,
    items: [
      { itemCode: '11.01', activity: 'Insulation', description: 'R-13/15 paredes, R-38 attic, vapor barrier crawlspace. TODOS los rough-ins deben estar aprobados primero.', responsable: 'Insulation contractor', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '11.02', activity: 'Insulation Inspection', description: 'Inspección de Oconee County. Todos rough-ins aprobados + R-values correctos. BLOQUEA DRYWALL.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '11.03', activity: 'Drywall Hang', description: 'Instalación de drywall 1/2" paredes y techo. 5/8" type X en garage (fire code).', responsable: 'Drywall contractor', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '11.04', activity: 'Drywall Tape, Mud, Sand', description: 'Cinta, masilla y lijado. 3 capas de compound para acabado liso. Crítico para pintura.', responsable: 'Drywall contractor', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '11.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '11.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 6 },
    ],
  },
  {
    code: 'F12', name: 'Interior Finishes', groupName: 'OBRA', order: 12,
    items: [
      { itemCode: '12.01', activity: 'Interior Paint', description: 'Pintura interior: primer + 2 capas de pintura. Paredes y cielorrasos. Colores según design package.', responsable: 'Painter', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '12.02', activity: 'Interior Trim (Baseboard, Casing)', description: 'Rodapiés, marcos de puertas y ventanas, crown molding si aplica.', responsable: 'Carpenter/Trim', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '12.03', activity: 'Interior Doors', description: 'Puertas interiores: colgado, alineación, manijas. Puertas de 2/8" estándar.', responsable: 'Carpenter', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '12.04', activity: 'Closets and Shelving', description: 'Sistemas de closets: estantes, barras, organizadores según plan.', responsable: 'Carpenter/Closet system', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '12.05', activity: 'Stairs (si aplica)', description: 'Escaleras si el plan incluye segunda planta o acceso a crawlspace. Handrail obligatorio.', responsable: 'Carpenter/Stair specialist', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '12.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '12.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '12.X3', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 8 },
    ],
  },
  {
    code: 'F13', name: 'Kitchen', groupName: 'OBRA', order: 13,
    items: [
      { itemCode: '13.01', activity: 'Kitchen Cabinets', description: 'Cabinetry: layout, materiales, colores según design. Semi-custom o RTA. Entrega y montaje.', responsable: 'Cabinet company/Carpenter', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '13.02', activity: 'Countertops', description: 'Countertops de cocina. Quartz o granite recomendado para el mercado de venta de SC.', responsable: 'Countertop fabricator', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '13.03', activity: 'Kitchen Backsplash', description: 'Tile backsplash de cocina. Instalado después del countertop.', responsable: 'Tile contractor', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '13.04', activity: 'Kitchen Plumbing Fixtures', description: 'Sink, faucet, disposal. Instalación del plomero después de cabinets.', responsable: 'Plumber', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '13.05', activity: 'Kitchen Electrical Fixtures', description: 'Under-cabinet lighting, outlets (GFCI obligatorio), range hood wiring.', responsable: 'Electrician', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '13.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 6 },
    ],
  },
  {
    code: 'F14', name: 'Flooring', groupName: 'OBRA', order: 14,
    items: [
      { itemCode: '14.01', activity: 'Subfloor Prep', description: 'Preparación del subfloor: nivelación, llenado de huecos, prime si es concreto.', responsable: 'Flooring contractor', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '14.02', activity: 'LVP / Hardwood Flooring', description: 'Instalación de pisos principales. LVP (Luxury Vinyl Plank) recomendado para SC por durabilidad/humedad.', responsable: 'Flooring contractor', unit: 'SF', valorPresupuestado: 0, order: 2 },
      { itemCode: '14.03', activity: 'Tile (Bathrooms/Utility)', description: 'Tile en baños, utility room, entrada. Impermeabilización en baños antes del tile.', responsable: 'Tile contractor', unit: 'SF', valorPresupuestado: 0, order: 3 },
      { itemCode: '14.04', activity: 'Carpet (Bedrooms si aplica)', description: 'Carpet en bedrooms si el diseño lo incluye. Instalar después de pintura.', responsable: 'Flooring contractor', unit: 'SF', valorPresupuestado: 0, order: 4 },
      { itemCode: '14.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 5 },
    ],
  },
  {
    code: 'F15', name: 'Plumbing & Bathroom Finishes', groupName: 'OBRA', order: 15,
    items: [
      { itemCode: '15.01', activity: 'Bathroom Vanities', description: 'Vanidades de baños: master + baño secundario + half bath. Instalación de plomero.', responsable: 'Plumber/Carpenter', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '15.02', activity: 'Bathroom Countertops / Tile Surround', description: 'Countertops de baños y tile en ducha/tub surround. Coordinar con flooring.', responsable: 'Tile/Countertop contractor', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '15.03', activity: 'Toilets', description: 'Instalación de toilets. 2 full baths = 2 toilets + 1 half bath = 1 toilet. Total: 3.', responsable: 'Plumber', unit: 'und', valorPresupuestado: 0, order: 3 },
      { itemCode: '15.04', activity: 'Shower/Tub Installation', description: 'Ducha y/o tub en baños. Acrylic surrounds o tile per design.', responsable: 'Plumber/Tile', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '15.05', activity: 'Faucets and Plumbing Trim', description: 'Faucets, shower valves, supply lines finales, soap dishes. Acabados de plomería.', responsable: 'Plumber', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '15.06', activity: 'Water Heater', description: 'Instalación del water heater (tank o tankless). Conectar gas/electric según diseño.', responsable: 'Plumber', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '15.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '15.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 8 },
    ],
  },
  {
    code: 'F16', name: 'Appliances & Extras', groupName: 'OBRA', order: 16,
    items: [
      { itemCode: '16.01', activity: 'Kitchen Appliances Package', description: 'Range/stove, dishwasher, microwave/range hood. Refrigerator opcional (mercado SC).', responsable: 'Owner/GC', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '16.02', activity: 'Electrical Fixtures (Lights)', description: 'Fixtures de iluminación: overhead lights, recessed cans, pendants, vanity lights.', responsable: 'Electrician', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '16.03', activity: 'HVAC Equipment Final', description: 'Instalación final de unidades HVAC: air handler interior + condensadora exterior. Startup y balanceo.', responsable: 'HVAC contractor', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '16.04', activity: 'Electrical Panel / Meter Base', description: 'Panel eléctrico final, meter base, conexión con Blue Ridge Electric. Coordinar utility.', responsable: 'Electrician', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '16.05', activity: 'Smoke & CO Detectors', description: 'Detectores de humo y CO. Requeridos por código en todas las habitaciones + pasillos.', responsable: 'Electrician', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '16.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 6 },
    ],
  },
  {
    code: 'F17', name: 'Final Touches & Landscaping', groupName: 'OBRA', order: 17,
    items: [
      { itemCode: '17.01', activity: 'Final Grading', description: 'Grading final del sitio: pendiente positiva away from house, drenaje correcto, preparación para siembra.', responsable: 'Grading contractor', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '17.02', activity: 'Landscaping / Sod', description: 'Instalación de sod o siembra de grass según plan de landscaping aprobado por ACC.', responsable: 'Landscaping contractor', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '17.03', activity: 'Punch List Execution', description: 'Corrección de todos los ítems del punch list previo a inspección final. Zero defects target.', responsable: 'GC + all subs', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '17.04', activity: 'Deep Clean', description: 'Limpieza profunda de toda la casa antes de inspecciones finales y fotografía.', responsable: 'Cleaning crew', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '17.05', activity: 'Mailbox Installation', description: 'Mailbox según spec de HOA Chickasaw. Algunos HOAs tienen estándar específico.', responsable: 'Owner/GC', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '17.06', activity: 'House Numbers', description: 'Números de la dirección permanentes visibles desde la calle.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '17.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '17.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 8 },
    ],
  },
  {
    code: 'F18', name: 'Inspecciones Finales', groupName: 'CIERRE', order: 18,
    items: [
      { itemCode: '18.01', activity: 'Final Building Inspection', description: 'TODAS las inspecciones anteriores aprobadas + punch list cerrado. GENERA CO. Oconee County.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '18.02', activity: 'Final Electrical Inspection', description: 'Todos los fixtures + GFCI + AFCI instalados y funcionando. Panel completo.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '18.03', activity: 'Final Plumbing Inspection', description: 'Todos los fixtures operativos + water heater + presión correcta.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '18.04', activity: 'Final HVAC Inspection', description: 'Equipos operativos + thermostat + filtros + Manual J cumplido.', responsable: 'Oconee County Inspector', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '18.05', activity: 'Certificate of Occupancy (CO)', description: 'Emitido por Oconee County. SIN CO NO SE PUEDE VENDER NI OCUPAR. Meta #1.', responsable: 'Oconee County', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '18.06', activity: 'HOA ACC Walk-through', description: 'Chickasaw ACC verifica colores, materiales, landscaping vs. aprobación original.', responsable: 'Chickasaw ACC', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '18.07', activity: 'HOA Compliance Letter', description: 'Carta de Chickasaw confirmando cumplimiento. Algunos buyers la exigen.', responsable: 'Chickasaw POA', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '18.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 8 },
      { itemCode: '18.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 9 },
    ],
  },
  {
    code: 'F19', name: 'Cierre y Entrega', groupName: 'CIERRE', order: 19,
    items: [
      { itemCode: '19.01', activity: 'Listing Photography', description: 'Fotografía profesional: exterior, interior, aérea (drone). Crítico para listing a $619K.', responsable: 'Photographer', unit: 'LS', valorPresupuestado: 0, order: 1 },
      { itemCode: '19.02', activity: 'Listing en MLS', description: 'Publicación en MLS por realtor. Target price $619,000.', responsable: 'Realtor', unit: 'LS', valorPresupuestado: 0, order: 2 },
      { itemCode: '19.03', activity: 'Staging (Optional)', description: 'Furniture staging para fotos y showings. Aumenta percepción de valor. Opcional en SC market.', responsable: 'Staging company', unit: 'LS', valorPresupuestado: 0, order: 3 },
      { itemCode: '19.04', activity: 'Final Draw (Draw Cierre)', description: 'Último draw del construction loan. Requiere CO + inspección final de Trinity.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 4 },
      { itemCode: '19.05', activity: 'Construction Loan Payoff', description: 'Pago del balance del construction loan en el closing de la venta. Guest & Brady lo coordina.', responsable: 'Title Company', unit: 'LS', valorPresupuestado: 0, order: 5 },
      { itemCode: '19.06', activity: 'Lien Waiver Final (GC)', description: 'Lien waiver final del GC y todos sus subs. Obligatorio antes de cerrar venta.', responsable: 'AMA, LLC + all subs', unit: 'LS', valorPresupuestado: 0, order: 6 },
      { itemCode: '19.07', activity: 'Closing de Venta', description: 'Cierre final con el buyer. Title company distribuye fondos, registra deed, payoff loan.', responsable: 'Title Company', unit: 'LS', valorPresupuestado: 0, order: 7 },
      { itemCode: '19.08', activity: 'Wire a SPV / Distribución Socios', description: 'Fondos de venta (ganancia) se wire al SPV Acosta Trust Homes y luego se distribuyen 50/50.', responsable: 'Owner', unit: 'LS', valorPresupuestado: 0, order: 8 },
      { itemCode: '19.09', activity: 'Dossier técnico de cierre', description: 'Paquete final: planos as-built, garantías subs, manuales, permisos cerrados, COIs. Para el buyer.', responsable: 'Owner/GC', unit: 'LS', valorPresupuestado: 0, order: 9 },
      { itemCode: '19.X1', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 10 },
      { itemCode: '19.X2', activity: '(ranura imprevisto)', description: '', responsable: '', unit: 'LS', valorPresupuestado: 0, order: 11 },
    ],
  },
]

const inspections = [
  { wbs: '05.A', tipo: 'Temp Power Approval', prerrequisitos: 'Electricista instala poste; Blue Ridge Electric aprueba antes de sitework', fase: '05 Preliminares', order: 1 },
  { wbs: '06.A', tipo: 'Erosion Control', prerrequisitos: 'Silt fence 100% instalado; previo a cualquier grading', fase: '06 Preparación Sitio', order: 2 },
  { wbs: '07.A', tipo: 'Footing Inspection', prerrequisitos: 'Excavación limpia + rebar colocado + formas listas. BLOQUEA VACIADO.', fase: '07 Foundation', order: 3 },
  { wbs: '07.B', tipo: 'Foundation / Crawlspace', prerrequisitos: 'Muros terminados + damp proofing + ventilación. Antes de backfill.', fase: '07 Foundation', order: 4 },
  { wbs: '07.C', tipo: 'POA Pre-Pour Notice (HOA)', prerrequisitos: 'Notificación 24h al POA Chickasaw ANTES del pour. Protocolo obligatorio HOA.', fase: '07 Foundation', order: 5 },
  { wbs: '08.A', tipo: 'Framing Inspection', prerrequisitos: 'Framing 100% completo incl. roof sheathing. Antes de house wrap.', fase: '08 Framing', order: 6 },
  { wbs: '09.A', tipo: 'Rough Electrical', prerrequisitos: '100% rough-in eléctrico completo. Antes de insulation. Bloquea drywall.', fase: '10 MEP', order: 7 },
  { wbs: '09.B', tipo: 'Rough Plumbing', prerrequisitos: 'DWV + supply lines + pressure test. Antes de insulation.', fase: '10 MEP', order: 8 },
  { wbs: '09.C', tipo: 'Rough HVAC', prerrequisitos: 'Ductwork + líneas refrigerante instaladas. Antes de insulation.', fase: '10 MEP', order: 9 },
  { wbs: '10.A', tipo: 'Insulation Inspection', prerrequisitos: 'R-13/15 walls, R-38 attic, vapor barrier crawlspace. Todos rough-ins aprobados. BLOQUEA DRYWALL.', fase: '11 Insulation', order: 10 },
  { wbs: '12.A', tipo: 'Final Building Inspection', prerrequisitos: 'TODAS las inspecciones anteriores aprobadas + punch list cerrado. GENERA CO.', fase: '18 Inspecciones Finales', order: 11 },
  { wbs: '12.B', tipo: 'Final Electrical', prerrequisitos: 'Todos los fixtures + GFCI + AFCI instalados y funcionando.', fase: '18 Inspecciones Finales', order: 12 },
  { wbs: '12.C', tipo: 'Final Plumbing', prerrequisitos: 'Todos los fixtures operativos + water heater + presión correcta.', fase: '18 Inspecciones Finales', order: 13 },
  { wbs: '12.D', tipo: 'Final HVAC', prerrequisitos: 'Equipos operativos + thermostat + filtros + Manual J cumplido.', fase: '18 Inspecciones Finales', order: 14 },
  { wbs: '12.E', tipo: 'Certificate of Occupancy', prerrequisitos: 'Emitido por Oconee County. Sin CO no se puede vender ni ocupar.', fase: '18 Inspecciones Finales', order: 15 },
  { wbs: '13.A', tipo: 'HOA ACC Walk-through', prerrequisitos: 'Chickasaw ACC verifica colores, materiales y landscaping vs. aprobación original.', fase: '18 Inspecciones Finales', order: 16 },
]

async function main() {
  const existing = await prisma.project.count()
  if (existing > 0) {
    console.log('✅ Database already seeded — skipping (data preserved)')
    return
  }

  console.log('Seeding Lote 87 — 218 N Foxglove Rd...')

  const project = await prisma.project.create({
    data: {
      name: 'LOTE 87 — 218 N Foxglove Rd',
      spv: 'Acosta Trust Homes, LLC',
      holding: 'Restrepo Acosta Global Holding LLC',
      address: '218 N Foxglove Rd, Westminster, SC 29693',
      county: 'Oconee County, SC',
      hoa: 'Chickasaw Point',
      parcelId: '323-01-06-002',
      lotAcres: 0.271,
      sfHeated: 2400,
      sfGarage: 971,
      sfPorches: 656,
      bedrooms: 3,
      bathrooms: '2.5',
      architecturalPlan: 'HPZ #2400-5 Crawlspace',
      foundationType: 'Crawlspace',
      permitNumber: 'BR26-000029',
      permitIssued: new Date('2026-01-27'),
      permitExpires: new Date('2026-07-27'),
      inspectorPhone: '(864) 718-1005',
      hoaPhone: '(864) 614-1109',
      gcName: 'AMA, LLC',
      gcPhone: '(864) 787-3290',
      gcLicense: 'Por confirmar',
      gcEmail: 'Por confirmar',
      lender: 'Hera Holdings LLC',
      loanNumber: 'HERA-2026-0066',
      loanAmount: 402350,
      day1Disbursement: 2000,
      interestReserve: 5000,
      holdback: 395350,
      interestRate: 0.085,
      loanTermMonths: 18,
      settlementDate: new Date('2026-03-25'),
      cashAtSettlement: 13349.36,
      closingCosts: 20349.36,
      settlementAgent: 'Guest & Brady, LLC',
      arv: 619000,
      constructionBudget: 465750,
      trinityName: 'Trinity Real Estate Solutions',
      trinityPhone: '888-573-8025',
      trinityEmail: 'info@trinityonline.com',
      targetCompletionDate: new Date('2026-08-26'),
      startDate: new Date('2026-03-25'),
      listingCommission: 0.03,
      buyerCommission: 0.03,
      targetListingPrice: 619000,
      contingencyPct: 0.08,
      targetMarginPct: 0.20,
      benchmarkSfTarget: 220,
      partners: {
        create: [
          { name: 'Juan David Restrepo', ownershipPct: 0.5, capitalAporte: 0, phone: '786-969-1295', email: 'proyectosrestrepoacosta@gmail.com', order: 1 },
          { name: 'Juan Camilo Acosta', ownershipPct: 0.5, capitalAporte: 0, order: 2 },
        ],
      },
      providers: {
        create: [
          { name: 'AMA, LLC', type: 'GC', phone: '(864) 787-3290' },
          { name: 'Hera Holdings LLC', type: 'Lender', phone: '' },
          { name: 'Trinity Real Estate Solutions', type: 'Inspector', phone: '888-573-8025', email: 'info@trinityonline.com' },
          { name: 'Guest & Brady, LLC', type: 'Title Company' },
          { name: 'Blue Ridge Electric Cooperative', type: 'Utility', phone: '864-878-6326' },
          { name: 'Chickasaw Point Utilities', type: 'Utility', phone: '864-614-1109' },
          { name: 'Oconee County', type: 'Authority', phone: '(864) 718-1005' },
          { name: 'Alto Capital Holdings', type: 'Lender (Lot)' },
        ],
      },
      draws: {
        create: [
          {
            drawNumber: 1,
            fechaSolicitud: new Date('2026-03-12'),
            fechaInspeccion: new Date('2026-03-16'),
            fechaWire: new Date('2026-03-25'),
            montoSolicitado: 0,
            elegibleTrinity: 94400,
            porcentajeFunded: 0.8488,
            netWire: 80131.06,
            upbPre: 7000,
            upbPost: 87131.06,
            saldoHoldback: 315218.94,
            notas: 'Inspección inicial: 20.27% completado',
            estado: 'WIRED',
          },
          {
            drawNumber: 2,
            fechaSolicitud: new Date('2026-04-20'),
            fechaInspeccion: new Date('2026-04-20'),
            fechaWire: new Date('2026-04-29'),
            montoSolicitado: 0,
            elegibleTrinity: 66600,
            porcentajeFunded: 0.8489,
            netWire: 56533.14,
            upbPre: 87131.06,
            upbPost: 143664.20,
            saldoHoldback: 258685.80,
            notas: 'Inspección Draw 2: 34.57% completado',
            estado: 'WIRED',
          },
          { drawNumber: 3, estado: 'EMPTY', upbPre: 143664.20, upbPost: 143664.20, saldoHoldback: 258685.80 },
          { drawNumber: 4, estado: 'EMPTY', upbPre: 143664.20, upbPost: 143664.20, saldoHoldback: 258685.80 },
          { drawNumber: 5, estado: 'EMPTY', upbPre: 143664.20, upbPost: 143664.20, saldoHoldback: 258685.80 },
          { drawNumber: 6, estado: 'EMPTY', upbPre: 143664.20, upbPost: 143664.20, saldoHoldback: 258685.80 },
          { drawNumber: 7, estado: 'EMPTY', upbPre: 143664.20, upbPost: 143664.20, saldoHoldback: 258685.80 },
          { drawNumber: 8, estado: 'EMPTY', upbPre: 143664.20, upbPost: 143664.20, saldoHoldback: 258685.80 },
        ],
      },
      inspections: {
        create: inspections,
      },
    },
  })

  for (const phaseData of phases) {
    const phase = await prisma.phase.create({
      data: {
        projectId: project.id,
        code: phaseData.code,
        name: phaseData.name,
        groupName: phaseData.groupName,
        order: phaseData.order,
      },
    })

    for (const item of phaseData.items) {
      await prisma.item.create({
        data: {
          phaseId: phase.id,
          itemCode: item.itemCode,
          activity: item.activity,
          description: item.description,
          responsable: item.responsable,
          unit: item.unit,
          valorPresupuestado: item.valorPresupuestado,
          order: item.order,
          estado: 'PENDIENTE',
        },
      })
    }
  }

  console.log(`✅ Proyecto creado: ${project.name}`)
  console.log(`✅ ${phases.length} fases creadas`)
  console.log(`✅ ${phases.reduce((s, p) => s + p.items.length, 0)} ítems creados`)
  console.log(`✅ 8 draws inicializados`)
  console.log(`✅ ${inspections.length} inspecciones creadas`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
